Manual Expense Tracking Feature
StuartGavidia/businessapp pull request #44
Opened 2024-04-10 21:06 UTC by jonahansmulcrone

built out functionality and ui components for a manual expense tracking feature. users can now create income transactions and regular (expense) transactions based on historical revenue/spending.

2024-04-11 21:49 UTC, StuartGavidia requested changes

2024-04-12 02:26 UTC, jonahansmulcrone commented on AnalyticsService/app/models.py
> +class IncomeTransaction(db.Model):
there will only be two types of transactions, regular (expenses) and income transactions. It's basically a self-reporting system for expenses and income.

2024-04-12 02:28 UTC, jonahansmulcrone commented on AnalyticsService/app/routes.py
> +        occurance=occurance,
thanks for pointing that out!

2024-04-12 02:29 UTC, jonahansmulcrone commented on client/src/features/Analytics/Analytics.tsx
> +                                                    <th style={{ fontWeight: 'bold', border: '1px solid #dddddd', textAlign: 'left', padding: '8px' }}>Account Name</th>
good call, I'll move the code to a css file

2024-04-12 02:31 UTC, jonahansmulcrone commented on client/src/features/Analytics/BudgetCard.tsx
>  import { Card, ProgressBar } from "react-bootstrap"
noted! I'll take care of this.

2024-04-12 19:26 UTC, StuartGavidia approved these changes
Looks good, nice pr!

2024-04-12 19:41 UTC, merged